package Langertha::Spec::Ollama;
# ABSTRACT: Pre-computed OpenAPI operations for Ollama
our $VERSION = '0.304';

# AUTO-GENERATED by maint/generate_spec_data.pl -- do not edit manually.
# Source: share/ollama.yaml (12 operations)

my $DATA;

sub data {
  $DATA //= {
    server_url => 'http://localhost:11434',
    operations => {
      'chat' => { method => 'POST', path => '/api/chat', content_type => 'application/json' },
      'copy' => { method => 'POST', path => '/api/copy', content_type => 'application/json' },
      'create' => { method => 'POST', path => '/api/create', content_type => 'application/json' },
      'delete' => { method => 'DELETE', path => '/api/delete', content_type => 'application/json' },
      'embed' => { method => 'POST', path => '/api/embed', content_type => 'application/json' },
      'generate' => { method => 'POST', path => '/api/generate', content_type => 'application/json' },
      'list' => { method => 'GET', path => '/api/tags' },
      'ps' => { method => 'GET', path => '/api/ps' },
      'pull' => { method => 'POST', path => '/api/pull', content_type => 'application/json' },
      'push' => { method => 'POST', path => '/api/push', content_type => 'application/json' },
      'show' => { method => 'POST', path => '/api/show', content_type => 'application/json' },
      'version' => { method => 'GET', path => '/api/version' },
    },
  };
  return $DATA;
}

1;
